services:

    backend:
      build:
        context: .
      container_name: calculator-backend
      ports:
        - "8080:8080"

    frontend:
      build:
        context: ./frontend
      container_name: calculator-frontend
      ports:
        - "3000:80"
      depends_on:
        - backend

